### ISSUE TITLE
Consider restyling the login toolbar

### ISSUE THREAD

**Issue by JSlote** [CarletonDevX/textbook-exchange#134] opened 2016-08-22 00:20 UTC
and maybe split out log in and sign up

**Comment by dpikt** [comment] 2016-08-22 04:12
Duplicate of #89?

**Comment by dpikt** [comment] 2016-08-22 04:30
And #109 ;)

**Comment by JSlote** [comment] 2016-08-23 17:14
In progress on jslote/restyle-main

**Comment by JSlote** [comment] 2016-08-23 18:54
Now in #142

**Closed** 2016-08-23 19:11 UTC
