### ISSUE TITLE
Registration edge cases

### ISSUE THREAD

**Issue by dpikt** [CarletonDevX/textbook-exchange#39] opened 2016-07-20 17:58 UTC

**Comment by dpikt** [comment] 2016-07-20 17:58
[] Registering, but the email address is already registered but not verified: ignore the extant registration and just overwrite it as if it were a new registration
[] Registering but already verified: server responds with 400 (bad request) and we tell the user "sorry, there's already an account associated with that email address"

**Comment by JSlote** [comment] 2016-07-20 20:20
Possible duplicate of #30 ?

**Comment by dpikt** [comment] 2016-07-22 00:02
Yeah I just left this here as a reminder to myself. Working on it presently

**Closed** 2016-07-22 00:45 UTC
Labels: min. viable prod.
